spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
        - id: web-service
          uri: lb://WEB-SERVICE
          predicates:
            - Path=/web/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
