spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-auth-service
          uri: lb://USER-AUTHENTICATION-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
