spring:
  application:
    name: auth-service
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: your-client-id
            clientSecret: your-client-secret
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: dbuser
    password: dbpass
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
