spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?useSSL=false
    username: dbuser
    password: dbpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8200

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
